@startuml
left to right direction
skinparam dpi 300

interface Image {
    +display(): void
}

class RealImage {
    -filename: String
    +RealImage(filename: String)
    -loadFromDisk(): void
    +display(): void
}

class ProxyImage {
    -realImage: RealImage
    -filename: String
    +ProxyImage(filename: String)
    +display(): void
}

class Client {
    +main(args: String[]): void
}

Image <|.. RealImage
Image <|.. ProxyImage

Client --> ProxyImage : uses
ProxyImage --> RealImage : lazy-load

@enduml
